name: l2l_shared
description: Shared admin/editor pages for L2L Sign app and dashboard
publish_to: "none"

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.11
  cloud_functions: ^5.6.0
  firebase_auth: ^5.6.0
  firebase_core: ^3.15.1
  firebase_storage: ^12.4.7
  firebase_messaging: ^15.2.9
  file_picker: ^10.2.0
  overlay_support: ^2.1.0
  provider: ^6.0.5
  http: ^1.4.0
  intl: any
  uuid: ^4.4.2
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

